### ISSUE TITLE
Hometown compatibility

### ISSUE THREAD

**Issue by thisisparker** [WesSouza/mastodon-flock#12]
Hi there! This tool looks excellent but I think it won't auth with instances running the popular [Hometown fork of Mastodon](https://github.com/hometown-fork/hometown). In particular, I and others get an incompatibleServerSoftware error when trying to auth to my instance at tech.intersects.art. If it's just a matter of checking for compatible version strings or similar, can I request you allow those? From an API perspective I think Hometown is so close that it won't create any issues.

**Comment by WesSouza** [comment]
I've published @ckolderup changes to preview, can you test if it works for your instance?

https://mastodon-flock-preview.vercel.app/
