### ISSUE TITLE
[bug] "Navigate to the home page" button resizes navigator to a very small size

### ISSUE THREAD

**Issue by claudiofreitas** [WesSouza/mastodon-flock#4]
**Reproduction steps:**

1. Open the "Web 1.0 Internet Navigator" (either through clicking About or Privacy Policy in the Desktop).
2. Click "Navigate to the home page" button. 
![image](https://user-images.githubusercontent.com/212832/206848535-28e60989-d21e-4317-8b3c-fbad55eb12ad.png)

3. Navigator opens the Mastodon Flock home page but resizes the window size to be very small

**Expected**
3. Navigator opens the Mastodon Flock home page without resizing

Before clicking "Home":
![image](https://user-images.githubusercontent.com/212832/206848946-4a302dbb-ccb6-416e-aa2c-132d96508707.png)

After clicking "Home":
![image](https://user-images.githubusercontent.com/212832/206848960-41828c9b-65a9-43bb-9b1d-6c0dbfef6bed.png)

--
Browser: Firefox Nightly 109.0a1 (2022-11-27) (64-bit)
OS: macOS Ventura v13.0.1 (Apple M1)

**Comment by WesSouza** [comment]
[meme gif of Peter Griffing trying to close blinds with the label "CSS"]

**Comment by WesSouza** [comment]
Fix coming soon
![localhost_3000_about](https://user-images.githubusercontent.com/126160/206857672-076379ac-259d-4aed-8d86-9fef5402150a.png)

**Comment by claudiofreitas** [comment]
Oh it was quick!
I was fiddling with the css trying to reach some result.
CSS won this one haha

**Comment by WesSouza** [comment]
@claudiofreitas https://mastodon-flock-preview.vercel.app/about?url=https%3A%2F%2Fmastodon-flock-preview.vercel.app

**Comment by claudiofreitas** [comment]
Nice! It doesn't minimize now.
But I think it introduced another bug.
Different from the screenshot that you posted above, the fix cannot create the "inception effect".

E.g. 
1. Click About
2. Click Home button
3. Close the Wizard
4. Click About (this one inside the navigator)
5. Icons disappear, but no new navigator is opened

I think in the current production code it's possible to open infinite navigators, and in your screenshot above as well :D

**Comment by WesSouza** [comment]
Weird, I'll try to fix it. 

Edit: @claudiofreitas can you try again?

**Comment by claudiofreitas** [comment]
@WesSouza Sorry I didn't see the edit (I think it doesn't notify)
I checked now and it is working in production, nice :D
