### ISSUE TITLE
[bug] Question mark icon in the system tray doesn't work on /desktop

### ISSUE THREAD

**Issue by claudiofreitas** [WesSouza/mastodon-flock#5]
**Reproduction steps:**

1. Click question icon
![image](https://user-images.githubusercontent.com/212832/206849054-18e41178-ed3b-433d-a30f-09c3b03687c3.png)
2. Nothing happens

**Expected:**

2. About Mastodon Flock to be displayed

**How to make the About Mastodon Flock to be displayed currently:**

1. Open Web 1.0 Internet Navigator (through clicking About or Privacy Policy)
2. Click Home button
3. Mastodon Flock gets loaded inside Internet Navigator (navigator is also resized)
4. Click same question icon, but inside the system tray inside the navigator
5. About Mastodon Flock gets displayed, but navigator is small so it's not possible to appreciate it
![image](https://user-images.githubusercontent.com/212832/206849487-7f34517c-eb8b-4310-9382-aa0a0fa892bb.png)

**Comment by WesSouza** [comment]
The window manager isn't in the desktop, I gotta add it so that works.
